### ISSUE TITLE
ModuleNotFoundError: No module named 'lightweight_gan'

### ISSUE THREAD

**Issue by imkelt** [lucidrains/transganformer#7]
Thank you very much for your work! I have encountered the following mistake. How can I solve this?
![image](https://user-images.githubusercontent.com/30486951/116173544-5bcef480-a73f-11eb-96c5-a37ba7166a4a.png)

**Comment by lucidrains** [comment]
Oops, fixed! https://github.com/lucidrains/transganformer/blob/main/transganformer/__init__.py

**Comment by imkelt** [comment]
Thanks very much for your reply!!!

**Comment by lucidrains** [comment]
@imkelt this repo is still a work in progress btw, don't expect stellar results yet!
